org: andersonkaiti
service: api-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs24.x
  memorySize: 128

package:
  individually: true

build:
  esbuild:
    sourcemap: false
    minify: true

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: GET
  getUserById:
    handler: src/functions/get-user-by-id.handler
    memorySize: 512
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
